package com.foodshare.controller;
import com.foodshare.model.*;import com.foodshare.repository.*;import org.springframework.web.bind.annotation.*;import org.springframework.security.access.AccessDeniedException;import org.springframework.transaction.annotation.Transactional;import java.security.Principal;import java.util.*;
@RestController @RequestMapping("/api/deliveries") @Transactional public class DeliveryController{
 private final DeliveryRepository deliveries;private final UserRepository users;private final RequestRepository requests;private final DonationRepository donations;public DeliveryController(DeliveryRepository d,UserRepository u,RequestRepository r,DonationRepository dn){deliveries=d;users=u;requests=r;donations=dn;}
 @GetMapping("/my") public List<Delivery> mine(Principal p){return deliveries.findAll().stream().filter(d->d.getVolunteer()==null||d.getVolunteer().getEmail().equals(p.getName())).toList();}
 @PutMapping("/{id}/accept") public Delivery accept(@PathVariable Integer id,Principal p){Delivery d=owned(id,p);if(!"ASSIGNED".equals(d.getStatus()))throw new IllegalArgumentException("Only assigned deliveries can be accepted.");if(d.getVolunteer()==null)d.setVolunteer(users.findByEmail(p.getName()).orElseThrow());d.setStatus("ACCEPTED");return deliveries.save(d);}
 @PutMapping("/{id}/pickup") public Delivery pickup(@PathVariable Integer id,Principal p){Delivery d=owned(id,p);if(!"ACCEPTED".equals(d.getStatus()))throw new IllegalArgumentException("Accept this delivery before pickup.");d.setStatus("PICKED_UP");d.getRequest().getDonation().setStatus("PICKED_UP");donations.save(d.getRequest().getDonation());return deliveries.save(d);}
 @PutMapping("/{id}/deliver") public Delivery deliver(@PathVariable Integer id,Principal p){Delivery d=owned(id,p);if(!"PICKED_UP".equals(d.getStatus()))throw new IllegalArgumentException("Mark the food as picked up before delivery.");d.setStatus("DELIVERED");d.getRequest().setStatus("DELIVERED");d.getRequest().getDonation().setStatus("DELIVERED");requests.save(d.getRequest());donations.save(d.getRequest().getDonation());return deliveries.save(d);}
 private Delivery owned(Integer id,Principal p){Delivery d=deliveries.findById(id).orElseThrow();if(d.getVolunteer()!=null&&!d.getVolunteer().getEmail().equals(p.getName()))throw new AccessDeniedException("This delivery belongs to another volunteer.");return d;}
}
