package com.foodshare.controller;
import com.foodshare.model.*;import com.foodshare.repository.*;import org.springframework.web.bind.annotation.*;import org.springframework.security.access.AccessDeniedException;import org.springframework.transaction.annotation.Transactional;import java.security.Principal;import java.util.*;
@RestController @RequestMapping("/api/requests") @Transactional public class RequestController{
 private final RequestRepository requests;private final DonationRepository donations;private final UserRepository users;private final DeliveryRepository deliveries;
 public RequestController(RequestRepository r,DonationRepository d,UserRepository u,DeliveryRepository de){requests=r;donations=d;users=u;deliveries=de;}
 @PostMapping public FoodRequest create(@RequestBody Map<String,Integer> body,Principal p){Integer donationId=body.get("donationId");if(donationId==null)throw new IllegalArgumentException("A donation must be selected.");Donation d=donations.findById(donationId).orElseThrow();if(!"AVAILABLE".equals(d.getStatus()))throw new IllegalArgumentException("This donation is not available.");Integer quantity=body.getOrDefault("quantity",d.getQuantity());if(quantity==null||quantity<1||quantity>d.getQuantity())throw new IllegalArgumentException("Requested quantity must be between 1 and the available quantity.");FoodRequest r=new FoodRequest();r.setDonation(d);r.setNgo(users.findByEmail(p.getName()).orElseThrow());r.setQuantity(quantity);r.setStatus("PENDING");d.setStatus("REQUESTED");donations.save(d);return requests.save(r);}
 @GetMapping("/my") public List<FoodRequest> mine(Principal p){return requests.findByNgoId(users.findByEmail(p.getName()).orElseThrow().getId());}@GetMapping("/{id}") public FoodRequest one(@PathVariable Integer id){return requests.findById(id).orElseThrow();}
 @PutMapping("/{id}/approve") public FoodRequest approve(@PathVariable Integer id,Principal p){FoodRequest r=ownedRequest(id,p);if(!"PENDING".equals(r.getStatus()))throw new IllegalArgumentException("Only pending requests can be approved.");r.setStatus("APPROVED");requests.save(r);if(!deliveries.existsByRequestId(id)){Delivery d=new Delivery();d.setRequest(r);d.setVolunteer(users.findFirstByRole("VOLUNTEER").orElse(null));d.setStatus("ASSIGNED");deliveries.save(d);}r.getDonation().setStatus("ASSIGNED");donations.save(r.getDonation());return r;}
 @PutMapping("/{id}/reject") public FoodRequest reject(@PathVariable Integer id,Principal p){FoodRequest r=ownedRequest(id,p);if(!"PENDING".equals(r.getStatus()))throw new IllegalArgumentException("Only pending requests can be rejected.");r.setStatus("REJECTED");r.getDonation().setStatus("AVAILABLE");donations.save(r.getDonation());return requests.save(r);}
 private FoodRequest ownedRequest(Integer id,Principal p){FoodRequest r=requests.findById(id).orElseThrow();User actor=users.findByEmail(p.getName()).orElseThrow();if(!"ADMIN".equals(actor.getRole())&&!r.getNgo().getId().equals(actor.getId()))throw new AccessDeniedException("You can only update your own requests.");return r;}
}
